from fpdf import FPDF
import tempfile
from datetime import datetime
import unicodedata

def remove_accents(input_str):
    if not isinstance(input_str, str):
        return str(input_str)
    nfkd_form = unicodedata.normalize('NFKD', input_str)
    return "".join([c for c in nfkd_form if not unicodedata.combining(c)])

class MedicalPDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'HOSPITAL MEDICAL RECORD', 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.cell(0, 10, 'Cardiovascular Risk Assessment Report', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def generate_pdf_report(patient_id, raw_input_data, prediction, probability):
    pdf = MedicalPDF()
    pdf.add_page()
    
    # Section 1
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, '1. Patient Information', 0, 1)
    
    pdf.set_font("Arial", size=12)
    pdf.cell(50, 8, 'Patient ID:', 0, 0)
    pdf.cell(0, 8, str(patient_id), 0, 1)
    pdf.cell(50, 8, 'Assessment Date:', 0, 0)
    pdf.cell(0, 8, datetime.now().strftime("%Y-%m-%d %H:%M:%S"), 0, 1)
    pdf.ln(5)
    
    # Section 2
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, '2. Clinical Indicators', 0, 1)
    
    pdf.set_font("Arial", size=12)
    # Define mapping to English for PDF
    eng_mapping = {
        "Tuổi": "Age",
        "Giới tính": "Sex",
        "Loại đau ngực": "Chest Pain Type",
        "Huyết áp": "Resting Blood Pressure",
        "Cholesterol": "Serum Cholesterol",
        "Đường huyết cao": "Fasting Blood Sugar > 120",
        "Điện tâm đồ": "Resting ECG",
        "Nhịp tim max": "Max Heart Rate",
        "Đau ngực gắng sức": "Exercise Induced Angina",
        "Suy giảm ST": "ST Depression",
        "Độ dốc ST": "Slope of Peak ST",
        "Mạch máu": "Number of Major Vessels",
        "Thalassemia": "Thalassemia"
    }

    for key, value in raw_input_data.items():
        eng_key = eng_mapping.get(key, remove_accents(key))
        safe_val = remove_accents(str(value))
        pdf.cell(60, 8, f'{eng_key}:', 0, 0)
        pdf.cell(0, 8, f'{safe_val}', 0, 1)
    
    pdf.ln(5)
    
    # Section 3
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, '3. AI Diagnosis Conclusion', 0, 1)
    
    pdf.set_font("Arial", 'B', 12)
    if prediction == 1:
        pdf.set_text_color(230, 57, 70)
        pdf.cell(0, 10, 'HIGH RISK OF CARDIOVASCULAR DISEASE DETECTED.', 0, 1)
        # Recommendation
        pdf.set_font("Arial", 'B', 10)
        pdf.cell(0, 10, 'Recommendation: Immediate consultation with cardiologist requested.', 0, 1)
    else:
        pdf.set_text_color(42, 157, 143)
        pdf.cell(0, 10, 'NO SIGNIFICANT RISK OF CARDIOVASCULAR DISEASE DETECTED.', 0, 1)
        pdf.set_font("Arial", 'B', 10)
        pdf.cell(0, 10, 'Recommendation: Maintain healthy lifestyle and regular checkups.', 0, 1)
        
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", size=12)
    pdf.cell(0, 10, f'Calculated Risk Probability: {probability*100:.2f}%', 0, 1)
    
    pdf.ln(10)
    pdf.set_font("Arial", 'I', 10)
    pdf.multi_cell(0, 6, "Disclaimer: This report is generated by an AI assistant based on clinical data. It represents a statistical risk assessment and DOES NOT replace a professional diagnosis by a qualified medical practitioner.")
    
    # Return as bytes
    pdf_bytes = bytes(pdf.output(dest='S'))
    return pdf_bytes
